### ISSUE TITLE
vending_machine SENSOR_THRESHOLD constant will need to be tweaked

### ISSUE THREAD

**Issue by NickMale** [Kalafut-organization/elephant_vending_machine_backend#44]
Once the actual machine is wired up the `SENSOR_THRESHOLD` value will need to be adjusted to reflect the distance between the sensor and whatever it's bouncing it's signal off of so that the sensor will only be triggered by appropriate interaction.

**Comment by brogers856** [comment]
Sonar sensors are no longer part of the device hardware
